<?php

namespace Universibo\Bundle\DidacticsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DegreeCourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DegreeCourseRepository extends EntityRepository
{
}