<?php

namespace Universibo\Bundle\DidacticsBundle\Entity;

use Universibo\Bundle\CoreBundle\Entity\Channel;

use Doctrine\ORM\EntityRepository;

/**
 * FacultyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyRepository extends EntityRepository
{
    /**
     * @param Channel $channel
     * @return number
     */
    public function findOneByChannel(Channel $channel)
    {
        return $this
            ->createQueryBuilder('f')
            ->where('f.channel = :channel')
            ->setParameter('channel', $channel)
            ->getFirstResult()
        ;
    }
}