services:
  universibo_core.repository.contact:
    class: Universibo\Bundle\CoreBundle\Entity\UserRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: ['Universibo\Bundle\CoreBundle\Entity\Contact']
  universibo_core.repository.group:
    class: Universibo\Bundle\CoreBundle\Entity\GroupRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: ['Universibo\Bundle\CoreBundle\Entity\Group']
  universibo_core.repository.person:
    class: Universibo\Bundle\CoreBundle\Entity\UserRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: ['Universibo\Bundle\CoreBundle\Entity\Person']
  universibo_core.repository.unibo_group:
    class: Universibo\Bundle\CoreBundle\Entity\UniboGroupRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: ['Universibo\Bundle\CoreBundle\Entity\UniboGroup']
  universibo_core.repository.user:
    class: Universibo\Bundle\CoreBundle\Entity\UserRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: ['Universibo\Bundle\CoreBundle\Entity\User']
  universibo_core.contact.service:
    class: Universibo\Bundle\CoreBundle\Contact\ContactService
    arguments:
      - '@doctrine.orm.entity_manager'
