<?php

namespace Universibo\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatchRenameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsernameFromId($id)
    {
        $user = $this->find($id);

        return $user instanceof User ? $user->getUsername() : null;
    }
    
    public function search($usernameQuery, $mailQuery)
    {
        $qb = $this->createQueryBuilder('u');
        
        if(strlen($usernameQuery) > 0) {
            $qb->andWhere('u.usernameCanonical LIKE ?0');
        } 
        
        if(strlen($mailQuery) > 0) {
            $qb->andWhere('u.emailCanonical LIKE ?1');
        }
        
        return 
            $qb -> getQuery()
                -> setParameters(array(mb_strtolower($usernameQuery), mb_strtolower($mailQuery)))
                -> getResult();
    }

    public function findCollaborators()
    {
        $qb = $this->createQueryBuilder('u');

        $qb->add('where', $qb->expr()->in('u.legacyGroups', array(4, 64)));

        return $qb->getQuery()->getResult();
    }

    /**
     * @param  User   $user
     * @return object
     */
    public function save(User $user)
    {
        $em = $this->getEntityManager();
        $user = $em->merge($user);
        $em->flush($user);
        
        return $user;
    }
}
