imports:
    - { resource: parameters.yml }    
    - { resource: security.yml }
    - { resource: mailer.yml }

framework:
    esi:             { enabled: true }
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    session: ~
    fragments:       { path: /_fragment }
# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    java: /usr/bin/java
    filters:
      cssrewrite: ~
      yui_js:
        jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
      yui_css:
        jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Doctrine Configuration
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
      forum:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%_forum3"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    auto_mapping: true



#jms_security_extra:
#    secure_controllers:  true
#    secure_all_services: false

fos_user:
    db_driver: orm
    user_class: 'Universibo\Bundle\CoreBundle\Entity\User'
    firewall_name: main
    group:
      group_class: 'Universibo\Bundle\CoreBundle\Entity\Group'

universibo_campus:
  api:
    uri: 'http://campus.unibo.it/cgi/'

universibo_shibboleth:
  idp_url:
    base: '%idp_url%'
    info: 'infoSSO.aspx'
    logout: 'prelogout.aspx'
  route:
    after_login:  'universibo_legacy_myuniversibo'
    after_logout:  'universibo_legacy_myuniversibo'
  claims:
    - eppn
    - givenName
    - idAnagraficaUnica
    - isMemberOf
    - sn
  user_provider: universibo_website.user.provider

ornicar_apc:
  host: %apc_host%
  web_dir: %kernel.root_dir%/../web
