parameters:
  antivirus_enabled: false
  antivirus_cmd:     /usr/bin/clamscan
  antivirus_opts:    '--quiet --recursive'
  
  alert_message: ~
  
  database_driver: 'pdo_pgsql'
  database_pear_driver: 'pgsql'
  database_host: '127.0.0.1'
  database_port: ''
  database_name: 'universibo'
  database_user: 'universibo'
  database_password: 'universibo'
  forum_api: 'http://www.universibo.dev/forum/api'
  mailer_transport: 'smtp'
  mailer_host: 'localhost'
  mailer_user: ''
  mailer_password: ''
  mailer_from: 'associazione.universibo@unibo.it'
  mailer_dev: 'dev_universibo@mama.ing.unibo.it'
  mailer_info: 'info_universibo@mama.ing.unibo.it'
  mailer_from_name: 'UniversiBO'
  sms_user: 'username'
  sms_password: 'password'
  sms_from: 'UniversiBO'
  locale: 'it'
  secret: '478919c22cdaff3fa4df28fab47eb46f'
  idp_url: 'https://idptest.unibo.it/adfs/ls/'
  academical_year: 2012
  apc_host: 'http://www.universibo.dev/'
  analytics_id: ''
