universibo_dashboard:
    resource: "@UniversiboDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

UniversiboCoreBundle:
    resource: "@UniversiboCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
UniversiboForumBundle:
    resource: "@UniversiboForumBundle/Resources/config/routing.yml"
    prefix:   /   

UniversiboWebsiteBundle:
    resource: "@UniversiboWebsiteBundle/Resources/config/routing.yml"
    prefix:   /
    
UniversiboLegacyBundle:
    resource: "@UniversiboLegacyBundle/Resources/config/routing.yml"
    prefix:   /

UniversiboShibbolethBundle:
    resource: "@UniversiboShibbolethBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

login:
    pattern: /login
    
logout:
    pattern: /logout

homepage:
    pattern: /
