universibo_dashboard:
    resource: "@UniversiboDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

UniversiboForumBundle:
    resource: "@UniversiboForumBundle/Resources/config/routing.yml"
    prefix:   /   

UniversiboMainBundle:
    resource: "@UniversiboMainBundle/Resources/config/routing.yml"
    prefix:   /
    
UniversiboLegacyBundle:
    resource: "@UniversiboLegacyBundle/Resources/config/routing.yml"
    prefix:   /

UniversiboShibbolethBundle:
    resource: "@UniversiboShibbolethBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

login:
    pattern: /login
    
logout:
    pattern: /logout

homepage:
    pattern: /
