services:
  universibo_website.feed.feed_generator:
    class: Universibo\Bundle\WebsiteBundle\Feed\FeedGenerator
    arguments:
      - '@universibo_legacy.repository.news.news_item'
      - '@router'
  universibo_website.twig.extension:
    class: Universibo\Bundle\WebsiteBundle\Twig\UniversiboExtension
    tags:
      -  { name: twig.extension }
  universibo_website.user.provider:
    class: Universibo\Bundle\WebsiteBundle\Security\User\UniversiboUserProvider
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@universibo_core.repository.person'
      - '@universibo_core.repository.user'
      - '@fos_user.user_manager'
      - '@universibo_core.repository.unibo_group'
      - '@logger'
    tags:
      -  { name: monolog.logger, channel: shibboleth }
  universibo_website.listener.privacy:
    class: Universibo\Bundle\WebsiteBundle\Listener\PrivacyListener
    arguments:
      - '@security.context'
      - '@router'
      - '@universibo_legacy.service.privacy'
      - '@universibo_forum.session'
      - '@universibo_website.contact.verification'
      - '@fos_user.user_manager'
    tags:
      -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  universibo_website.listener.auth.failure:
    class: Universibo\Bundle\WebsiteBundle\Listener\AuthenticationFailedListener
    arguments:
      - '@mailer'
      - '@logger'
      - '@router'
      - '@templating'
      - '%mailer_from%'
      - '%mailer_from_name%'
      - '%mailer_dev%'
      - '%mailer_info%'
      -  { name: kernel.event_listener, event: universibo_shibboleth.auth_failed, method: onAuthenticationFailed }
  universibo_website.privacy.logout_handler:
    class: Universibo\Bundle\WebsiteBundle\Security\Http\Logout\PrivacyLogoutHandler
  universibo_website.encoder.md5:
    class: Universibo\Bundle\WebsiteBundle\Security\Encoder\Md5Encoder
  universibo_website.encoder.sha1:
    class: Universibo\Bundle\WebsiteBundle\Security\Encoder\Sha1Encoder
  universibo_website.merge.user:
    class: Universibo\Bundle\WebsiteBundle\Entity\Merge\UserMerger
    arguments:
      - '@universibo_core.repository.user'
      - '@universibo_legacy.repository.files.file_item'
      - '@universibo_legacy.repository.commenti.commento_item'
      - '@universibo_legacy.repository.news.news_item'
      - '@universibo_legacy.repository.links.link'
      - '@universibo_legacy.repository.ruolo'
      - '@universibo_legacy.repository.docente'
      - '@universibo_forum.dao.post'
      - '@universibo_forum.dao.user'
  universibo_website.contact.verification:
    class: Universibo\Bundle\WebsiteBundle\Contact\VerificationService
    arguments:
      - '@mailer'
      - '%mailer_from%'
      - '%mailer_from_name%'
      - '@templating'
      - '@doctrine.orm.entity_manager'
  universibo_website.menu_builder:
    class: Universibo\Bundle\WebsiteBundle\Menu\MenuBuilder
    scope: request
    arguments:
      - '@knp_menu.factory'
      - '@security.context'
      - '@universibo_forum.router'
      - '@universibo_legacy.acl'
      - '@universibo_legacy.routing.channel'
      - '@universibo_legacy.repository.canale2'
      - '@universibo_legacy.repository.ruolo'

  universibo_website.menu.main:
    class: Knp\Menu\MenuItem
    factory_service: universibo_website.menu_builder
    factory_method: createMainMenu
    arguments:
      - '@request'
    scope: request
    tags:
      - { name: knp_menu.menu, alias: main }
