/* Generated By:JavaCC: Do not edit this line. CLParserConstants.java */
package parser;

public interface CLParserConstants {

  int EOF = 0;
  int LBRACE = 6;
  int RBRACE = 7;
  int IN = 8;
  int OUT = 9;
  int END = 10;
  int NUM = 11;
  int TIME = 12;
  int EVENT = 13;
  int DEF = 14;
  int STARTS = 15;
  int WHEN = 16;
  int ENDS = 17;
  int DOLLARO = 18;
  int NS = 19;
  int AT = 20;
  int RANGE_SEP = 21;
  int LIST_SEP = 22;
  int DEF_OP = 23;
  int O_BRACE = 24;
  int C_BRACE = 25;
  int VARIABILE = 26;
  int NOME = 27;
  int STAR = 28;
  int STOP = 29;
  int COMMA = 30;
  int OPEN = 31;
  int CLOSE = 32;
  int LETTER = 33;
  int DIGIT = 34;
  int CIFRA = 35;
  int ID = 36;
  int STRINGA = 37;
  int SYMBOL = 38;
  int NSLEFT = 39;
  int NSRIGHT = 45;
  int CALL = 46;
  int OP = 47;

  int DEFAULT = 0;
  int Var = 1;
  int Param = 2;
  int WithinNsbody = 3;
  int InnerBody = 4;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"{\"",
    "\"}\"",
    "\"IN\"",
    "\"OUT\"",
    "\";\"",
    "<NUM>",
    "\"TIME\"",
    "\"EVENT\"",
    "\"DEF\"",
    "\"STARTS\"",
    "\"WHEN\"",
    "\"ENDS\"",
    "\"$\"",
    "\"#\"",
    "\"@\"",
    "\"..\"",
    "\",\"",
    "\"OP\"",
    "\"(\"",
    "\")\"",
    "<VARIABILE>",
    "<NOME>",
    "\"*\"",
    "\";\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "<LETTER>",
    "<DIGIT>",
    "<CIFRA>",
    "<ID>",
    "<STRINGA>",
    "<SYMBOL>",
    "\"[\"",
    "\"[\"",
    "<token of kind 41>",
    "\"]\"",
    "\"[\"",
    "<token of kind 44>",
    "\"]\"",
    "\"->\"",
    "<OP>",
  };

}
