<?php

namespace Universibo\Bundle\WebsiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatchRenameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsernameFromId($id)
    {
        $user = $this->find($id);

        return $user instanceof User ? $user->getUsername() : null;
    }

    public function findCollaborators()
    {
        $qb = $this->createQueryBuilder('u');

        $qb->add('where', $qb->expr()->in('u.legacyGroups', array(4, 64)));

        return $qb->getQuery()->getResult();
    }
}
