<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121030125240 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user ADD encoder_name VARCHAR(15) DEFAULT NULL");
        
        $this->addSql("UPDATE fos_user fu SET salt = (SELECT u.salt FROM utente u WHERE u.id_utente = fu.id)");
        $this->addSql("UPDATE fos_user fu SET password = (SELECT u.password FROM utente u WHERE u.id_utente = fu.id)");
        $this->addSql("UPDATE fos_user fu SET encoder_name = (SELECT u.algoritmo FROM utente u WHERE u.id_utente = fu.id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user DROP encoder_name");
    }
}
