<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121030140048 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE utente_id_utente_seq");
        $this->addSql("DROP TABLE utente CASCADE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE utente_id_utente_seq INCREMENT BY 1 MINVALUE 1 START 1");
        
        $this->addSql("CREATE TABLE utente (id_utente INT DEFAULT nextval('utente_id_utente_seq') NOT NULL, username VARCHAR(25) NOT NULL, password VARCHAR(40) NOT NULL, email VARCHAR(255) DEFAULT NULL, ultimo_login INT DEFAULT NULL, inoltro_email CHAR(255) DEFAULT 'N', ad_username VARCHAR(255) DEFAULT '''::character varying', groups INT DEFAULT NULL, ban CHAR(255) DEFAULT 'N', notifica INT NOT NULL, phone VARCHAR(15) DEFAULT '''::character varying', default_style VARCHAR(10) DEFAULT '''::character varying', sospeso CHAR(255) DEFAULT 'N' NOT NULL, algoritmo VARCHAR(8) DEFAULT 'md5' NOT NULL, salt VARCHAR(8) DEFAULT '''::character varying' NOT NULL, PRIMARY KEY(id_utente))");
        $this->addSql("CREATE UNIQUE INDEX utente_username_key ON utente (username)");
    }
}
