<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121031130458 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user DROP member_of");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE argomento_id_argomento_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE argomento_set_id_argomento__seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE canale_id_canale_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE file_categoria_id_file_categoria_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE file_id_file_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE file_studente_commenti_id_commento_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE file_tipo_id_file_tipo_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE forums_auth_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE help_id_help_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE informativa_id_informativa_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE link_id_link_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE news_id_news_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE notifica_id_notifica_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_banlist_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_categories_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_disallow_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_forum_prune_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_groups_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_posts_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_privmsgs_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_ranks_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_search_wordlist_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_smilies_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_themes_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_topics_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_users_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_vote_desc_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE phpbb_words_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE prg_sdop_id_sdop_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE prg_sdoppiamento_r_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE prg_sdoppiamento_rr_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE stat_accessi_id_accesso_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE stat_download_id_download_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE stat_login_id_login_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE stat_visite_id_visita_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE studente_richi_id_argomento_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE studente_richiede_id_utente_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE utente_richiede_a_id_utente_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE utente_richied_id_argomento_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE backup_black (id_utente INT DEFAULT NULL)");
        $this->addSql("CREATE TABLE backup_notifica (id_notifica INT DEFAULT NULL, urgente CHAR(255) DEFAULT NULL, messaggio TEXT DEFAULT NULL, titolo VARCHAR(200) DEFAULT NULL, timestamp INT DEFAULT NULL, destinatario VARCHAR(200) DEFAULT NULL, eliminata CHAR(255) DEFAULT NULL)");
        $this->addSql("CREATE TABLE canale (id_canale SERIAL NOT NULL, tipo_canale INT NOT NULL, nome_canale VARCHAR(200) DEFAULT NULL, immagine VARCHAR(50) DEFAULT NULL, visite INT NOT NULL, ultima_modifica INT DEFAULT NULL, permessi_groups INT DEFAULT NULL, files_attivo CHAR(255) DEFAULT NULL, news_attivo CHAR(255) DEFAULT NULL, forum_attivo CHAR(255) DEFAULT NULL, id_forum INT DEFAULT NULL, group_id INT DEFAULT NULL, links_attivo CHAR(255) DEFAULT NULL, files_studenti_attivo CHAR(255) DEFAULT NULL, PRIMARY KEY(id_canale))");
        $this->addSql("CREATE TABLE classi_corso (cod_corso VARCHAR(4) NOT NULL, desc_corso VARCHAR(150) NOT NULL, id_canale INT DEFAULT NULL, cat_id INT DEFAULT NULL, cod_doc VARCHAR(6) DEFAULT NULL, cod_fac VARCHAR(4) DEFAULT NULL, categoria INT DEFAULT NULL, PRIMARY KEY(cod_corso))");
        $this->addSql("CREATE TABLE classi_corso2 (cod_corso VARCHAR(4) DEFAULT NULL, desc_corso VARCHAR(150) DEFAULT NULL)");
        $this->addSql("CREATE UNIQUE INDEX classi_corso2_cod_corso_key ON classi_corso2 (cod_corso)");
        $this->addSql("CREATE TABLE classi_indirizzi (cod_ind VARCHAR(3) NOT NULL, desc_ind VARCHAR(150) NOT NULL, PRIMARY KEY(cod_ind))");
        $this->addSql("CREATE TABLE classi_materie (cod_materia VARCHAR(5) NOT NULL, desc_materia VARCHAR(150) NOT NULL, PRIMARY KEY(cod_materia))");
        $this->addSql("CREATE TABLE classi_materie2 (cod_materia VARCHAR(5) NOT NULL, desc_materia VARCHAR(150) NOT NULL, PRIMARY KEY(cod_materia))");
        $this->addSql("CREATE TABLE classi_orientamenti (cod_ori VARCHAR(3) NOT NULL, desc_ori VARCHAR(150) NOT NULL, PRIMARY KEY(cod_ori))");
        $this->addSql("CREATE TABLE collaboratore (id_utente INT NOT NULL, intro TEXT DEFAULT NULL, recapito VARCHAR(255) DEFAULT NULL, obiettivi TEXT DEFAULT NULL, foto VARCHAR(255) DEFAULT NULL, ruolo VARCHAR(255) DEFAULT NULL, show CHAR(255) DEFAULT 'N' NOT NULL, PRIMARY KEY(id_utente))");
        $this->addSql("CREATE TABLE docente (cod_doc VARCHAR(6) NOT NULL, id_utente INT NOT NULL, nome_doc VARCHAR(150) DEFAULT NULL, docente_contattato INT DEFAULT 0, id_mod INT DEFAULT NULL, PRIMARY KEY(cod_doc))");
        $this->addSql("CREATE UNIQUE INDEX docente_cod_doc_key ON docente (cod_doc)");
        $this->addSql("CREATE TABLE docente2 (cod_doc VARCHAR(6) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, nome_doc VARCHAR(150) DEFAULT NULL)");
        $this->addSql("CREATE UNIQUE INDEX docente2_cod_doc_key ON docente2 (cod_doc)");
        $this->addSql("CREATE TABLE docente_contatti (cod_doc VARCHAR(6) NOT NULL, stato INT DEFAULT 1 NOT NULL, id_utente_assegnato INT DEFAULT NULL, ultima_modifica INT DEFAULT NULL, report TEXT DEFAULT '''::text' NOT NULL, eliminato CHAR(255) DEFAULT 'N' NOT NULL, PRIMARY KEY(cod_doc))");
        $this->addSql("COMMENT ON COLUMN docente_contatti.eliminato IS 'Eliminazione logica'");
        $this->addSql("CREATE TABLE esami_info (id_argomento INT NOT NULL, programma_esame TEXT DEFAULT '''::text', programma_esame_link VARCHAR(128) DEFAULT '''::character varying', testi_consigliati TEXT DEFAULT '''::text', modalita_esame TEXT DEFAULT '''::text', faq_link VARCHAR(128) DEFAULT '''::character varying', obiettivi_esame TEXT DEFAULT '''::text', obiettivi_esame_link VARCHAR(128) DEFAULT '''::character varying', modalita_esame_link VARCHAR(128) DEFAULT '''::character varying', testi_consigliati_link VARCHAR(128) DEFAULT '''::character varying', homepage_esame_link VARCHAR(128) DEFAULT '''::character varying', appelli_esame TEXT DEFAULT '''::text', appelli_esame_link VARCHAR(128) DEFAULT '''::character varying', PRIMARY KEY(id_argomento))");
        $this->addSql("CREATE TABLE facolta (cod_fac VARCHAR(4) NOT NULL, desc_fac VARCHAR(150) NOT NULL, url_facolta VARCHAR(80) DEFAULT NULL, id_canale INT DEFAULT NULL, cod_doc CHAR(255) DEFAULT NULL, PRIMARY KEY(cod_fac))");
        $this->addSql("CREATE TABLE file (id_file INT DEFAULT "file_id_file_seq" NOT NULL, permessi_download INT NOT NULL, permessi_visualizza INT NOT NULL, id_utente INT NOT NULL, titolo VARCHAR(150) NOT NULL, descrizione TEXT DEFAULT NULL, data_inserimento INT NOT NULL, data_modifica INT NOT NULL, dimensione INT NOT NULL, download INT NOT NULL, nome_file VARCHAR(256) NOT NULL, id_categoria INT NOT NULL, id_tipo_file INT NOT NULL, hash_file VARCHAR(40) NOT NULL, password VARCHAR(40) DEFAULT NULL, eliminato CHAR(255) NOT NULL, PRIMARY KEY(id_file))");
        $this->addSql("CREATE TABLE file2 (id_file INT DEFAULT "file_id_file_seq" NOT NULL, titolo VARCHAR(150) DEFAULT NULL, data INT NOT NULL, descrizione TEXT NOT NULL, id_autore INT NOT NULL, dimensione INT NOT NULL, contatore SMALLINT NOT NULL, collegato INT DEFAULT NULL, estensione VARCHAR(3) DEFAULT NULL, id_moderatore INT DEFAULT NULL, categoria CHAR(255) DEFAULT NULL, nome_file VARCHAR(256) DEFAULT NULL)");
        $this->addSql("CREATE TABLE file_canale (id_file INT NOT NULL, id_canale INT NOT NULL, PRIMARY KEY(id_file, id_canale))");
        $this->addSql("CREATE INDEX file_canale_id_canale_key ON file_canale (id_canale)");
        $this->addSql("CREATE INDEX file_canale_id_file_key ON file_canale (id_file)");
        $this->addSql("CREATE TABLE file_categoria (id_file_categoria SERIAL NOT NULL, descrizione VARCHAR(128) NOT NULL, PRIMARY KEY(id_file_categoria))");
        $this->addSql("CREATE TABLE file_keywords (id_file INT NOT NULL, keyword VARCHAR(50) NOT NULL, PRIMARY KEY(id_file, keyword))");
        $this->addSql("CREATE TABLE file_riguarda_argomento (id_argomento INT NOT NULL, id_file INT NOT NULL, eliminato CHAR(255) DEFAULT 'N' NOT NULL, data_inserimento INT NOT NULL, PRIMARY KEY(id_argomento, id_file))");
        $this->addSql("CREATE TABLE file_studente_canale (id_file INT NOT NULL, id_canale INT NOT NULL, PRIMARY KEY(id_file))");
        $this->addSql("CREATE TABLE file_studente_commenti (id_commento SERIAL NOT NULL, id_file INT NOT NULL, id_utente INT NOT NULL, commento TEXT NOT NULL, voto INT NOT NULL, eliminato CHAR(255) NOT NULL, PRIMARY KEY(id_commento))");
        $this->addSql("CREATE UNIQUE INDEX file_studente_commenti_id_file_key ON file_studente_commenti (id_file, id_utente, id_commento)");
        $this->addSql("CREATE TABLE file_tipo (id_file_tipo SERIAL NOT NULL, descrizione VARCHAR(128) NOT NULL, pattern_riconoscimento VARCHAR(128) NOT NULL, icona VARCHAR(256) NOT NULL, info_aggiuntive TEXT DEFAULT NULL, PRIMARY KEY(id_file_tipo))");
        $this->addSql("CREATE TABLE help (id_help SERIAL NOT NULL, titolo VARCHAR(255) NOT NULL, contenuto TEXT NOT NULL, ultima_modifica INT NOT NULL, indice INT NOT NULL, PRIMARY KEY(id_help))");
        $this->addSql("CREATE TABLE help_riferimento (riferimento VARCHAR(32) NOT NULL, id_help INT NOT NULL, PRIMARY KEY(riferimento, id_help))");
        $this->addSql("CREATE TABLE help_topic (riferimento VARCHAR(32) NOT NULL, titolo VARCHAR(256) NOT NULL, indice INT NOT NULL, PRIMARY KEY(riferimento))");
        $this->addSql("CREATE TABLE prg_insegnamento (anno_accademico NUMERIC(4, 0) NOT NULL, cod_corso VARCHAR(4) NOT NULL, cod_ind VARCHAR(3) NOT NULL, cod_ori VARCHAR(3) NOT NULL, cod_materia VARCHAR(5) NOT NULL, anno_corso VARCHAR(1) NOT NULL, cod_materia_ins VARCHAR(5) NOT NULL, anno_corso_ins VARCHAR(1) NOT NULL, cod_ril VARCHAR(3) NOT NULL, cod_modulo VARCHAR(5) NOT NULL, cod_doc VARCHAR(6) NOT NULL, flag_titolare_modulo CHAR(255) NOT NULL, id_canale INT DEFAULT NULL, cod_orario SMALLINT DEFAULT NULL, tipo_ciclo CHAR(255) NOT NULL, cod_ate VARCHAR(3) DEFAULT '010', anno_corso_universibo VARCHAR(1) DEFAULT NULL)");
        $this->addSql("CREATE TABLE info_didattica (id_canale INT NOT NULL, programma TEXT DEFAULT '''::text' NOT NULL, programma_link VARCHAR(256) DEFAULT '''::character varying' NOT NULL, testi_consigliati TEXT DEFAULT '''::text' NOT NULL, testi_consigliati_link VARCHAR(256) DEFAULT '''::character varying' NOT NULL, modalita TEXT DEFAULT '''::text' NOT NULL, modalita_link VARCHAR(256) DEFAULT '''::character varying' NOT NULL, obiettivi_esame TEXT DEFAULT '''::text' NOT NULL, obiettivi_esame_link VARCHAR(256) DEFAULT '''::character varying' NOT NULL, appelli TEXT DEFAULT '''::text' NOT NULL, appelli_link VARCHAR(256) DEFAULT '''::character varying' NOT NULL, homepage_alternativa_link VARCHAR(256) DEFAULT '''::character varying' NOT NULL, orario_ics_link VARCHAR(256) DEFAULT '''::character varying' NOT NULL, PRIMARY KEY(id_canale))");
        $this->addSql("CREATE TABLE informativa (id_informativa INT DEFAULT "informativa_id_informativa_seq" NOT NULL, data_pubblicazione INT NOT NULL, data_fine INT DEFAULT NULL, testo TEXT NOT NULL, PRIMARY KEY(id_informativa))");
        $this->addSql("CREATE TABLE input_classi_corsi (cod_corso VARCHAR(4) NOT NULL, desc_corso VARCHAR(150) NOT NULL, cod_fac VARCHAR(4) DEFAULT NULL)");
        $this->addSql("CREATE TABLE input_classi_materie (cod_materia VARCHAR(5) NOT NULL, desc_materia VARCHAR(150) NOT NULL)");
        $this->addSql("CREATE TABLE input_docente (cod_doc VARCHAR(6) NOT NULL, nome_doc VARCHAR(150) NOT NULL)");
        $this->addSql("CREATE TABLE input_esami_attivi (anno_accademico NUMERIC(4, 0) NOT NULL, cod_corso VARCHAR(4) NOT NULL, cod_ind VARCHAR(3) NOT NULL, cod_ori VARCHAR(3) NOT NULL, cod_materia VARCHAR(5) NOT NULL, anno_corso VARCHAR(1) NOT NULL, cod_materia_ins VARCHAR(5) NOT NULL, anno_corso_ins VARCHAR(1) NOT NULL, cod_ril VARCHAR(3) NOT NULL, cod_modulo VARCHAR(5) NOT NULL, cod_attivita VARCHAR(5) DEFAULT '0' NOT NULL, prog_cronologico SMALLINT DEFAULT '0' NOT NULL, cod_doc VARCHAR(6) NOT NULL, flag_titolare_modulo CHAR(255) NOT NULL, id_canale INT DEFAULT NULL, cod_orario SMALLINT DEFAULT NULL, tipo_ciclo CHAR(255) NOT NULL, cod_ate VARCHAR(3) DEFAULT '010', anno_corso_universibo VARCHAR(1) DEFAULT NULL)");
        $this->addSql("CREATE TABLE input_sdoppiamenti_attivi (anno_accademico NUMERIC(4, 0) NOT NULL, anno_corso VARCHAR(1) NOT NULL, anno_corso_ins VARCHAR(1) NOT NULL, cod_corso VARCHAR(4) NOT NULL, cod_ind VARCHAR(3) NOT NULL, cod_materia VARCHAR(5) NOT NULL, cod_materia_ins VARCHAR(5) NOT NULL, cod_ori VARCHAR(3) NOT NULL, cod_ril VARCHAR(3) NOT NULL, flag_mutuato CHAR(255) NOT NULL, flag_comune CHAR(255) NOT NULL, tipo_ciclo CHAR(255) NOT NULL, anno_accademico_fis NUMERIC(4, 0) DEFAULT NULL, cod_corso_fis VARCHAR(4) DEFAULT NULL, cod_ind_fis VARCHAR(3) DEFAULT NULL, cod_ori_fis VARCHAR(3) DEFAULT NULL, cod_materia_fis VARCHAR(5) DEFAULT NULL, anno_corso_fis VARCHAR(1) DEFAULT NULL, cod_materia_ins_fis VARCHAR(5) DEFAULT NULL, anno_corso_ins_fis VARCHAR(1) DEFAULT NULL, cod_ril_fis VARCHAR(3) DEFAULT NULL, cod_ate VARCHAR(3) DEFAULT '010', cod_ate_fis VARCHAR(3) DEFAULT '010', anno_corso_universibo VARCHAR(1) DEFAULT NULL, PRIMARY KEY(anno_accademico, anno_corso, anno_corso_ins, cod_corso, cod_ind, cod_materia, cod_materia_ins, cod_ori, cod_ril))");
        $this->addSql("CREATE TABLE prg_sdoppiamento (anno_accademico NUMERIC(4, 0) NOT NULL, anno_corso VARCHAR(1) NOT NULL, anno_corso_ins VARCHAR(1) NOT NULL, cod_corso VARCHAR(4) NOT NULL, cod_ind VARCHAR(3) NOT NULL, cod_materia VARCHAR(5) NOT NULL, cod_materia_ins VARCHAR(5) NOT NULL, cod_ori VARCHAR(3) NOT NULL, cod_ril VARCHAR(3) NOT NULL, flag_mutuato CHAR(255) NOT NULL, flag_comune CHAR(255) NOT NULL, tipo_ciclo CHAR(255) NOT NULL, anno_accademico_fis NUMERIC(4, 0) DEFAULT NULL, cod_corso_fis VARCHAR(4) DEFAULT NULL, cod_ind_fis VARCHAR(3) DEFAULT NULL, cod_ori_fis VARCHAR(3) DEFAULT NULL, cod_materia_fis VARCHAR(5) DEFAULT NULL, anno_corso_fis VARCHAR(1) DEFAULT NULL, cod_materia_ins_fis VARCHAR(5) DEFAULT NULL, anno_corso_ins_fis VARCHAR(1) DEFAULT NULL, cod_ril_fis VARCHAR(3) DEFAULT NULL, cod_ate VARCHAR(3) DEFAULT '010', cod_ate_fis VARCHAR(3) DEFAULT '010', anno_corso_universibo VARCHAR(1) DEFAULT NULL, id_sdop INT DEFAULT prg_sdop_id_sdop_seq NOT NULL, PRIMARY KEY(anno_accademico, anno_corso, anno_corso_ins, cod_corso, cod_ind, cod_materia, cod_materia_ins, cod_ori, cod_ril))");
        $this->addSql("CREATE TABLE link (id_link SERIAL NOT NULL, id_canale INT NOT NULL, id_utente INT NOT NULL, uri VARCHAR(255) NOT NULL, label VARCHAR(128) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id_link))");
        $this->addSql("CREATE TABLE news (id_news INT DEFAULT "news_id_news_seq" NOT NULL, titolo VARCHAR(150) NOT NULL, data_inserimento INT NOT NULL, data_scadenza INT DEFAULT NULL, notizia TEXT DEFAULT NULL, id_utente INT NOT NULL, eliminata CHAR(255) DEFAULT 'N' NOT NULL, flag_urgente CHAR(255) DEFAULT 'N' NOT NULL, data_modifica INT DEFAULT NULL, PRIMARY KEY(id_news))");
        $this->addSql("CREATE TABLE news_canale (id_news INT NOT NULL, id_canale INT NOT NULL, PRIMARY KEY(id_news, id_canale))");
        $this->addSql("CREATE INDEX news_canale_id_canale_key ON news_canale (id_canale)");
        $this->addSql("CREATE INDEX news_canale_id_news_key ON news_canale (id_news)");
        $this->addSql("CREATE TABLE news2 (id_news INT DEFAULT "news_id_news_seq" NOT NULL, titolo VARCHAR(150) NOT NULL, data_inserimento INT NOT NULL, data_scadenza INT DEFAULT NULL, notizia TEXT DEFAULT NULL, id_utente INT NOT NULL, id_argomento INT DEFAULT NULL, eliminata CHAR(255) DEFAULT 'N' NOT NULL)");
        $this->addSql("CREATE TABLE notifica (id_notifica SERIAL NOT NULL, urgente CHAR(255) NOT NULL, messaggio TEXT NOT NULL, titolo VARCHAR(200) NOT NULL, timestamp INT NOT NULL, destinatario VARCHAR(200) NOT NULL, eliminata CHAR(255) NOT NULL, PRIMARY KEY(id_notifica))");
        $this->addSql("CREATE INDEX notifica_eliminata ON notifica (eliminata)");
        $this->addSql("CREATE INDEX notifica_timestamp ON notifica (timestamp)");
        $this->addSql("CREATE TABLE orientamenti (cod_corso VARCHAR(4) NOT NULL, cod_ind VARCHAR(3) NOT NULL, cod_ori VARCHAR(3) NOT NULL, cod_fac VARCHAR(4) NOT NULL, PRIMARY KEY(cod_corso, cod_ind, cod_ori))");
        $this->addSql("CREATE TABLE prg_insegnamento2 (anno_accademico NUMERIC(4, 0) NOT NULL, cod_corso VARCHAR(4) NOT NULL, cod_ind VARCHAR(3) NOT NULL, cod_ori VARCHAR(3) NOT NULL, cod_materia VARCHAR(5) NOT NULL, anno_corso VARCHAR(1) NOT NULL, cod_materia_ins VARCHAR(5) NOT NULL, anno_corso_ins VARCHAR(1) NOT NULL, cod_ril VARCHAR(3) NOT NULL, cod_modulo VARCHAR(5) NOT NULL, cod_doc VARCHAR(6) NOT NULL, flag_titolare_modulo CHAR(255) NOT NULL, id_argomento INT DEFAULT NULL, cod_orario SMALLINT DEFAULT NULL, tipo_ciclo CHAR(255) NOT NULL, cod_ate VARCHAR(3) DEFAULT '010', anno_corso_universibo VARCHAR(1) DEFAULT NULL)");
        $this->addSql("CREATE TABLE prg_sdoppiamento2 (anno_accademico NUMERIC(4, 0) NOT NULL, anno_corso VARCHAR(1) NOT NULL, anno_corso_ins VARCHAR(1) NOT NULL, cod_corso VARCHAR(4) NOT NULL, cod_ind VARCHAR(3) NOT NULL, cod_materia VARCHAR(5) NOT NULL, cod_materia_ins VARCHAR(5) NOT NULL, cod_ori VARCHAR(3) NOT NULL, cod_ril VARCHAR(3) NOT NULL, flag_mutuato CHAR(255) NOT NULL, flag_comune CHAR(255) NOT NULL, tipo_ciclo CHAR(255) NOT NULL, anno_accademico_fis NUMERIC(4, 0) DEFAULT NULL, cod_corso_fis VARCHAR(4) DEFAULT NULL, cod_ind_fis VARCHAR(3) DEFAULT NULL, cod_ori_fis VARCHAR(3) DEFAULT NULL, cod_materia_fis VARCHAR(5) DEFAULT NULL, anno_corso_fis VARCHAR(1) DEFAULT NULL, cod_materia_ins_fis VARCHAR(5) DEFAULT NULL, anno_corso_ins_fis VARCHAR(1) DEFAULT NULL, cod_ril_fis VARCHAR(3) DEFAULT NULL, cod_ate VARCHAR(3) DEFAULT '010', cod_ate_fis VARCHAR(3) DEFAULT '010', anno_corso_universibo VARCHAR(1) DEFAULT NULL, PRIMARY KEY(anno_accademico, anno_corso, anno_corso_ins, cod_corso, cod_ind, cod_materia, cod_materia_ins, cod_ori, cod_ril))");
        $this->addSql("CREATE TABLE rb_docente (idutente INT NOT NULL, nomeoggetto CHAR(255) DEFAULT NULL, guiduser CHAR(255) DEFAULT NULL, logonname VARCHAR(50) DEFAULT NULL, nome VARCHAR(30) DEFAULT NULL, cognome VARCHAR(40) DEFAULT NULL, prefissonome VARCHAR(15) DEFAULT NULL, suffissonome VARCHAR(10) DEFAULT NULL, sesso SMALLINT DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, cod_doc VARCHAR(6) DEFAULT NULL, nomeoggettostruttura CHAR(255) DEFAULT NULL, descrizionestruttura VARCHAR(100) DEFAULT NULL, PRIMARY KEY(idutente))");
        $this->addSql("CREATE TABLE rb_email (idutente INT NOT NULL, seqemailutente SMALLINT NOT NULL, descrizioneemailutente VARCHAR(50) DEFAULT NULL, PRIMARY KEY(idutente, seqemailutente))");
        $this->addSql("CREATE TABLE rb_telefono (idutente INT NOT NULL, seqtelutente SMALLINT NOT NULL, descrizionetelutente VARCHAR(28) DEFAULT NULL, voice SMALLINT DEFAULT NULL, fax SMALLINT DEFAULT NULL, tipotel VARCHAR(15) DEFAULT NULL, PRIMARY KEY(idutente, seqtelutente))");
        $this->addSql("CREATE TABLE rub_docente (cod_doc VARCHAR(6) DEFAULT NULL, nome VARCHAR(30) DEFAULT NULL, cognome VARCHAR(40) DEFAULT NULL, prefissonome VARCHAR(15) DEFAULT NULL, sesso SMALLINT DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, descrizionestruttura VARCHAR(100) DEFAULT NULL, flag_origine SMALLINT DEFAULT NULL)");
        $this->addSql("CREATE TABLE rub_email (cod_doc VARCHAR(6) DEFAULT NULL, seqemailutente SMALLINT DEFAULT NULL, descrizioneemailutente VARCHAR(50) DEFAULT NULL)");
        $this->addSql("CREATE TABLE rub_telefono (cod_doc VARCHAR(6) DEFAULT NULL, seqtelutente SMALLINT DEFAULT NULL, descrizionetelutente VARCHAR(28) DEFAULT NULL, voice SMALLINT DEFAULT NULL, fax SMALLINT DEFAULT NULL)");
        $this->addSql("CREATE TABLE stat_accessi (id_accesso INT DEFAULT "stat_accessi_id_accesso_seq" NOT NULL, id_sessione VARCHAR(32) NOT NULL, id_visita INT DEFAULT NULL, ip VARCHAR(15) DEFAULT NULL, browser VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id_accesso))");
        $this->addSql("CREATE TABLE stat_argomento (id_visita INT NOT NULL, id_argomento INT NOT NULL, flag_utente_argomento CHAR(255) DEFAULT NULL, PRIMARY KEY(id_visita))");
        $this->addSql("CREATE TABLE utente_canale (id_utente INT NOT NULL, id_canale INT NOT NULL, ultimo_accesso INT DEFAULT NULL, ruolo INT DEFAULT NULL, my_universibo CHAR(255) DEFAULT NULL, notifica INT DEFAULT NULL, nascosto CHAR(255) DEFAULT 'N', nome VARCHAR(60) DEFAULT NULL, PRIMARY KEY(id_utente, id_canale))");
        $this->addSql("CREATE TABLE stat_download (id_download INT DEFAULT "stat_download_id_download_seq" NOT NULL, id_utente INT NOT NULL, id_argomento INT NOT NULL, id_file INT NOT NULL, id_visita INT DEFAULT NULL, PRIMARY KEY(id_download))");
        $this->addSql("CREATE TABLE stat_login (id_login INT DEFAULT "stat_login_id_login_seq" NOT NULL, id_visita INT DEFAULT NULL, risoluzione SMALLINT DEFAULT NULL, PRIMARY KEY(id_login))");
        $this->addSql("CREATE TABLE tmp_docenti_recenti (id_utente INT DEFAULT NULL, username VARCHAR(25) DEFAULT NULL, password VARCHAR(40) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, ultimo_login INT DEFAULT NULL, inoltro_email CHAR(255) DEFAULT NULL, ad_username VARCHAR(255) DEFAULT NULL, groups INT DEFAULT NULL, ban CHAR(255) DEFAULT NULL, notifica INT DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, default_style VARCHAR(10) DEFAULT NULL, sospeso CHAR(255) DEFAULT NULL, algoritmo VARCHAR(8) DEFAULT NULL, salt VARCHAR(8) DEFAULT NULL, last_news INT DEFAULT NULL, last_file INT DEFAULT NULL)");
        $this->addSql("CREATE TABLE stat_visite (id_visita INT DEFAULT "stat_visite_id_visita_seq" NOT NULL, id_accesso INT NOT NULL, id_utente INT NOT NULL, root_pagina VARCHAR(32) NOT NULL, id_pagina INT DEFAULT NULL, time INT NOT NULL, pagina_precedente VARCHAR(256) NOT NULL, pagina_visita VARCHAR(256) NOT NULL, PRIMARY KEY(id_visita))");
        $this->addSql("CREATE TABLE tmp_docenti_mai (id_utente INT DEFAULT NULL, username VARCHAR(25) DEFAULT NULL, password VARCHAR(40) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, ultimo_login INT DEFAULT NULL, inoltro_email CHAR(255) DEFAULT NULL, ad_username VARCHAR(255) DEFAULT NULL, groups INT DEFAULT NULL, ban CHAR(255) DEFAULT NULL, notifica INT DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, default_style VARCHAR(10) DEFAULT NULL, sospeso CHAR(255) DEFAULT NULL, algoritmo VARCHAR(8) DEFAULT NULL, salt VARCHAR(8) DEFAULT NULL, last_news INT DEFAULT NULL, last_file INT DEFAULT NULL)");
        $this->addSql("CREATE TABLE tmp_docenti_news_file (id_utente INT DEFAULT NULL, username VARCHAR(25) DEFAULT NULL, password VARCHAR(40) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, ultimo_login INT DEFAULT NULL, inoltro_email CHAR(255) DEFAULT NULL, ad_username VARCHAR(255) DEFAULT NULL, groups INT DEFAULT NULL, ban CHAR(255) DEFAULT NULL, notifica INT DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, default_style VARCHAR(10) DEFAULT NULL, sospeso CHAR(255) DEFAULT NULL, algoritmo VARCHAR(8) DEFAULT NULL, salt VARCHAR(8) DEFAULT NULL, last_news INT DEFAULT NULL, last_file INT DEFAULT NULL)");
        $this->addSql("CREATE TABLE tmp_docenti_vecchi (id_utente INT DEFAULT NULL, username VARCHAR(25) DEFAULT NULL, password VARCHAR(40) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, ultimo_login INT DEFAULT NULL, inoltro_email CHAR(255) DEFAULT NULL, ad_username VARCHAR(255) DEFAULT NULL, groups INT DEFAULT NULL, ban CHAR(255) DEFAULT NULL, notifica INT DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, default_style VARCHAR(10) DEFAULT NULL, sospeso CHAR(255) DEFAULT NULL, algoritmo VARCHAR(8) DEFAULT NULL, salt VARCHAR(8) DEFAULT NULL, last_news INT DEFAULT NULL, last_file INT DEFAULT NULL)");
        $this->addSql("CREATE TABLE tmp_doppioni2 (id_utente INT DEFAULT NULL, username VARCHAR(25) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, ad_username VARCHAR(255) DEFAULT NULL, ultimo_login INT DEFAULT NULL, post INT DEFAULT NULL)");
        $this->addSql("ALTER TABLE questionario ALTER id_questionario SET  DEFAULT "questionario_id_questionari_seq"");
        $this->addSql("ALTER TABLE questionario ALTER attiv_offline SET  DEFAULT 'N'");
        $this->addSql("ALTER TABLE questionario ALTER attiv_moderatore SET  DEFAULT 'N'");
        $this->addSql("ALTER TABLE questionario ALTER attiv_contenuti SET  DEFAULT 'N'");
        $this->addSql("ALTER TABLE questionario ALTER attiv_test SET  DEFAULT 'N'");
        $this->addSql("ALTER TABLE questionario ALTER attiv_grafica SET  DEFAULT 'N'");
        $this->addSql("ALTER TABLE questionario ALTER attiv_prog SET  DEFAULT 'N'");
        $this->addSql("ALTER TABLE step_log ALTER id_step SET  DEFAULT "step_id_step_seq"");
        $this->addSql("DROP INDEX "primary"");
        $this->addSql("CREATE SEQUENCE contacts_id_seq");
        $this->addSql("SELECT setval('contacts_id_seq', (SELECT MAX(id) FROM contacts))");
        $this->addSql("ALTER TABLE contacts ALTER id SET DEFAULT nextval('contacts_id_seq')");
        $this->addSql("CREATE SEQUENCE fos_group_id_seq");
        $this->addSql("SELECT setval('fos_group_id_seq', (SELECT MAX(id) FROM fos_group))");
        $this->addSql("ALTER TABLE fos_group ALTER id SET DEFAULT nextval('fos_group_id_seq')");
        $this->addSql("CREATE SEQUENCE people_id_seq");
        $this->addSql("SELECT setval('people_id_seq', (SELECT MAX(id) FROM people))");
        $this->addSql("ALTER TABLE people ALTER id SET DEFAULT nextval('people_id_seq')");
        $this->addSql("ALTER TABLE fos_user ADD member_of VARCHAR(15) DEFAULT NULL");
        $this->addSql("CREATE SEQUENCE fos_user_id_seq");
        $this->addSql("SELECT setval('fos_user_id_seq', (SELECT MAX(id) FROM fos_user))");
        $this->addSql("ALTER TABLE fos_user ALTER id SET DEFAULT nextval('fos_user_id_seq')");
        $this->addSql("ALTER TABLE fos_user ALTER groups SET  DEFAULT 0");
        $this->addSql("ALTER TABLE fos_user ALTER username_locked SET  DEFAULT 'true'");
    }
}
