<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121221214920 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE collaboratore_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        
        $this->addSql("ALTER TABLE collaboratore DROP CONSTRAINT collaboratore_pkey");
        
        $this->addSql('DELETE FROM collaboratore c WHERE NOT EXISTS (SELECT u.* FROM fos_user u WHERE c.id_utente = u.id)');
        
        $this->addSql("ALTER TABLE collaboratore ADD id INT NOT NULL DEFAULT nextval('collaboratore_id_seq')");
        $this->addSql("ALTER TABLE collaboratore ALTER id_utente DROP NOT NULL");
        $this->addSql("ALTER TABLE collaboratore ALTER show TYPE VARCHAR(1)");
        $this->addSql("ALTER TABLE collaboratore ADD CONSTRAINT FK_B6092A05F872060D FOREIGN KEY (id_utente) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_B6092A05F872060D ON collaboratore (id_utente)");
        $this->addSql("ALTER TABLE collaboratore ADD PRIMARY KEY (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE collaboratore DROP id");
        $this->addSql("DROP SEQUENCE collaboratore_id_seq");
        
        $this->addSql("ALTER TABLE collaboratore ALTER id_utente SET NOT NULL");
        $this->addSql("ALTER TABLE collaboratore ALTER show SET  DEFAULT 'N'");
        $this->addSql("ALTER TABLE collaboratore ALTER show TYPE CHAR(255)");
        $this->addSql("ALTER TABLE collaboratore DROP CONSTRAINT FK_B6092A05F872060D");
        $this->addSql("DROP INDEX UNIQ_B6092A05F872060D");
        //$this->addSql("DROP INDEX "primary"");
        $this->addSql("ALTER TABLE collaboratore ADD PRIMARY KEY (id_utente)");
    }
}
