<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120619172115 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user_user_group DROP CONSTRAINT fk_b3c77447a76ed395");
        $this->addSql("ALTER TABLE fos_user_user_group DROP CONSTRAINT fk_b3c77447fe54d947");
        $this->addSql("ALTER TABLE collaboratore DROP CONSTRAINT fk_b6092a05f872060d");
        $this->addSql("DROP SEQUENCE fos_user_group_id_seq");
        $this->addSql("DROP SEQUENCE fos_user_user_id_seq");
        $this->addSql("DROP SEQUENCE utente_id_utente_seq");
        $this->addSql("CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE fos_comments_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE collaborators (user_id INT NOT NULL, intro TEXT DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, contact VARCHAR(255) DEFAULT NULL, goals TEXT DEFAULT NULL, picture VARCHAR(255) DEFAULT NULL, show BOOLEAN NOT NULL, PRIMARY KEY(user_id))");
        $this->addSql("CREATE TABLE users (id INT NOT NULL, name VARCHAR(255) NOT NULL, roles TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1483A5E95E237E06 ON users (name)");
        $this->addSql("COMMENT ON COLUMN users.roles IS '(DC2Type:array)'");
        $this->addSql("CREATE TABLE fos_threads (id VARCHAR(255) NOT NULL, permalink VARCHAR(255) NOT NULL, is_commentable BOOLEAN NOT NULL, num_comments INT NOT NULL, last_comment_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE fos_comments (id INT NOT NULL, thread_id VARCHAR(255) DEFAULT NULL, body TEXT NOT NULL, ancestors VARCHAR(1024) NOT NULL, depth INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_F5BF9406E2904019 ON fos_comments (thread_id)");
        $this->addSql("ALTER TABLE collaborators ADD CONSTRAINT FK_42DD9F54A76ED395 FOREIGN KEY (user_id) REFERENCES users(id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE fos_comments ADD CONSTRAINT FK_F5BF9406E2904019 FOREIGN KEY (thread_id) REFERENCES fos_threads(id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("DROP TABLE collaboratore");
        $this->addSql("DROP TABLE fos_user_user");
        $this->addSql("DROP TABLE fos_user_group");
        $this->addSql("DROP TABLE fos_user_user_group");
        $this->addSql("DROP TABLE utente");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE collaborators DROP CONSTRAINT FK_42DD9F54A76ED395");
        $this->addSql("ALTER TABLE fos_comments DROP CONSTRAINT FK_F5BF9406E2904019");
        $this->addSql("DROP SEQUENCE users_id_seq");
        $this->addSql("DROP SEQUENCE fos_comments_id_seq");
        $this->addSql("CREATE SEQUENCE fos_user_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE fos_user_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE utente_id_utente_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE collaboratore (id_utente INT NOT NULL, intro TEXT DEFAULT NULL, ruolo VARCHAR(255) DEFAULT NULL, recapito VARCHAR(255) DEFAULT NULL, obiettivi TEXT DEFAULT NULL, foto VARCHAR(255) DEFAULT NULL, show VARCHAR(1) NOT NULL, PRIMARY KEY(id_utente))");
        $this->addSql("CREATE TABLE fos_user_user (id INT NOT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked BOOLEAN NOT NULL, expired BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, credentials_expired BOOLEAN NOT NULL, credentials_expire_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_of_birth TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, firstname VARCHAR(64) DEFAULT NULL, lastname VARCHAR(64) DEFAULT NULL, website VARCHAR(64) DEFAULT NULL, biography VARCHAR(255) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, phone VARCHAR(64) DEFAULT NULL, facebook_uid VARCHAR(255) DEFAULT NULL, facebook_name VARCHAR(255) DEFAULT NULL, facebook_data TEXT DEFAULT NULL, twitter_uid VARCHAR(255) DEFAULT NULL, twitter_name VARCHAR(255) DEFAULT NULL, twitter_data TEXT DEFAULT NULL, gplus_uid VARCHAR(255) DEFAULT NULL, gplus_name VARCHAR(255) DEFAULT NULL, gplus_data TEXT DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, two_step_code VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX uniq_c560d76192fc23a8 ON fos_user_user (username_canonical)");
        $this->addSql("CREATE UNIQUE INDEX uniq_c560d761a0d96fbf ON fos_user_user (email_canonical)");
        $this->addSql("COMMENT ON COLUMN fos_user_user.roles IS '(DC2Type:array)'");
        $this->addSql("CREATE TABLE fos_user_group (id INT NOT NULL, name VARCHAR(255) NOT NULL, roles TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX uniq_583d1f3e5e237e06 ON fos_user_group (name)");
        $this->addSql("COMMENT ON COLUMN fos_user_group.roles IS '(DC2Type:array)'");
        $this->addSql("CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY(user_id, group_id))");
        $this->addSql("CREATE INDEX idx_b3c77447a76ed395 ON fos_user_user_group (user_id)");
        $this->addSql("CREATE INDEX idx_b3c77447fe54d947 ON fos_user_user_group (group_id)");
        $this->addSql("CREATE TABLE utente (id_utente INT NOT NULL, username VARCHAR(25) NOT NULL, password VARCHAR(40) NOT NULL, email VARCHAR(255) DEFAULT NULL, ultimo_login INT DEFAULT NULL, ad_username VARCHAR(255) DEFAULT NULL, groups INT DEFAULT NULL, notifica INT DEFAULT NULL, ban VARCHAR(1) NOT NULL, phone VARCHAR(15) DEFAULT NULL, sospeso VARCHAR(1) NOT NULL, algoritmo VARCHAR(8) NOT NULL, salt VARCHAR(8) NOT NULL, PRIMARY KEY(id_utente))");
        $this->addSql("ALTER TABLE collaboratore ADD CONSTRAINT fk_b6092a05f872060d FOREIGN KEY (id_utente) REFERENCES utente(id_utente) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE fos_user_user_group ADD CONSTRAINT fk_b3c77447a76ed395 FOREIGN KEY (user_id) REFERENCES fos_user_user(id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE fos_user_user_group ADD CONSTRAINT fk_b3c77447fe54d947 FOREIGN KEY (group_id) REFERENCES fos_user_group(id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("DROP TABLE collaborators");
        $this->addSql("DROP TABLE users");
        $this->addSql("DROP TABLE fos_threads");
        $this->addSql("DROP TABLE fos_comments");
    }
}
