<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121011154244 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        
        $this->addSql("CREATE SEQUENCE people_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE people (id INT NOT NULL, unibo_id INT DEFAULT NULL, given_name VARCHAR(160) NOT NULL, surname VARCHAR(160) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_28166A266C57F6ED ON people (unibo_id)");
        $this->addSql("ALTER TABLE fos_user DROP given_name");
        $this->addSql("ALTER TABLE fos_user DROP surname");
        $this->addSql("ALTER TABLE fos_user ADD CONSTRAINT FK_957A6479217BBB47 FOREIGN KEY (person_id) REFERENCES people (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("CREATE INDEX IDX_957A6479217BBB47 ON fos_user (person_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user DROP CONSTRAINT FK_957A6479217BBB47");
        $this->addSql("DROP SEQUENCE people_id_seq");
        $this->addSql("DROP TABLE people");
        
        $this->addSql("ALTER TABLE fos_user ADD given_name VARCHAR(160) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD surname VARCHAR(160) DEFAULT NULL");
    }
}
