<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120619172954 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE questionario_id_questionari_seq");
        $this->addSql("CREATE SEQUENCE questionnaires_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE questionnaires (id INT NOT NULL, name VARCHAR(100) NOT NULL, surname VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, availableTime INT NOT NULL, onlineTime INT NOT NULL, moderator BOOLEAN NOT NULL, content BOOLEAN NOT NULL, test BOOLEAN NOT NULL, graphics BOOLEAN NOT NULL, designing BOOLEAN NOT NULL, notes TEXT NOT NULL, degreeCourse VARCHAR(100) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("DROP TABLE questionario");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE questionnaires_id_seq");
        $this->addSql("CREATE SEQUENCE questionario_id_questionari_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE questionario (id_questionario INT NOT NULL, data INT NOT NULL, nome VARCHAR(50) NOT NULL, cognome VARCHAR(50) NOT NULL, mail VARCHAR(50) NOT NULL, telefono VARCHAR(50) NOT NULL, tempo_disp SMALLINT NOT NULL, tempo_internet SMALLINT NOT NULL, attiv_offline VARCHAR(255) NOT NULL, attiv_moderatore VARCHAR(255) NOT NULL, attiv_contenuti VARCHAR(255) NOT NULL, attiv_test VARCHAR(255) NOT NULL, attiv_grafica VARCHAR(255) NOT NULL, attiv_prog VARCHAR(255) NOT NULL, altro TEXT NOT NULL, id_utente INT NOT NULL, cdl VARCHAR(50) NOT NULL, PRIMARY KEY(id_questionario))");
        $this->addSql("DROP TABLE questionnaires");
    }
}
