<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120619152248 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE TABLE news_channel (news_id INT NOT NULL, channel_id INT NOT NULL, PRIMARY KEY(news_id, channel_id))");
        $this->addSql("CREATE INDEX IDX_F51D92A1B5A459A0 ON news_channel (news_id)");
        $this->addSql("CREATE INDEX IDX_F51D92A172F5A1AA ON news_channel (channel_id)");
        $this->addSql("ALTER TABLE news_channel ADD CONSTRAINT FK_F51D92A1B5A459A0 FOREIGN KEY (news_id) REFERENCES News(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE news_channel ADD CONSTRAINT FK_F51D92A172F5A1AA FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP TABLE news_channel");
    }
}
