<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120619174100 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE questionario_id_questionari_seq");
        $this->addSql("CREATE SEQUENCE questionnaires_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Link_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE questionnaires (id INT NOT NULL, name VARCHAR(100) NOT NULL, surname VARCHAR(100) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, availableTime INT NOT NULL, onlineTime INT NOT NULL, moderator BOOLEAN NOT NULL, content BOOLEAN NOT NULL, test BOOLEAN NOT NULL, graphics BOOLEAN NOT NULL, designing BOOLEAN NOT NULL, notes TEXT NOT NULL, degreeCourse VARCHAR(100) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Link (id INT NOT NULL, uri VARCHAR(255) NOT NULL, label VARCHAR(100) NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("DROP TABLE questionario");
        $this->addSql("ALTER TABLE users ADD enabled BOOLEAN NOT NULL");
        $this->addSql("ALTER TABLE users ADD last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE users ADD locked BOOLEAN NOT NULL");
        $this->addSql("ALTER TABLE users ADD expired BOOLEAN NOT NULL");
        $this->addSql("ALTER TABLE users ADD expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE users ADD confirmation_token VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE users ADD password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE users ADD credentials_expired BOOLEAN NOT NULL");
        $this->addSql("ALTER TABLE users ADD credentials_expire_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL");
        $this->addSql("ALTER TABLE users RENAME COLUMN name TO password");
        $this->addSql("DROP INDEX uniq_1483a5e95e237e06");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1483A5E992FC23A8 ON users (username_canonical)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_1483A5E9A0D96FBF ON users (email_canonical)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE questionnaires_id_seq");
        $this->addSql("DROP SEQUENCE Link_id_seq");
        $this->addSql("CREATE SEQUENCE questionario_id_questionari_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE questionario (id_questionario INT NOT NULL, data INT NOT NULL, nome VARCHAR(50) NOT NULL, cognome VARCHAR(50) NOT NULL, mail VARCHAR(50) NOT NULL, telefono VARCHAR(50) NOT NULL, tempo_disp SMALLINT NOT NULL, tempo_internet SMALLINT NOT NULL, attiv_offline VARCHAR(255) NOT NULL, attiv_moderatore VARCHAR(255) NOT NULL, attiv_contenuti VARCHAR(255) NOT NULL, attiv_test VARCHAR(255) NOT NULL, attiv_grafica VARCHAR(255) NOT NULL, attiv_prog VARCHAR(255) NOT NULL, altro TEXT NOT NULL, id_utente INT NOT NULL, cdl VARCHAR(50) NOT NULL, PRIMARY KEY(id_questionario))");
        $this->addSql("DROP TABLE questionnaires");
        $this->addSql("DROP TABLE Link");
        $this->addSql("ALTER TABLE users ADD name VARCHAR(255) NOT NULL");
        $this->addSql("ALTER TABLE users DROP username");
        $this->addSql("ALTER TABLE users DROP username_canonical");
        $this->addSql("ALTER TABLE users DROP email");
        $this->addSql("ALTER TABLE users DROP email_canonical");
        $this->addSql("ALTER TABLE users DROP enabled");
        $this->addSql("ALTER TABLE users DROP salt");
        $this->addSql("ALTER TABLE users DROP password");
        $this->addSql("ALTER TABLE users DROP last_login");
        $this->addSql("ALTER TABLE users DROP locked");
        $this->addSql("ALTER TABLE users DROP expired");
        $this->addSql("ALTER TABLE users DROP expires_at");
        $this->addSql("ALTER TABLE users DROP confirmation_token");
        $this->addSql("ALTER TABLE users DROP password_requested_at");
        $this->addSql("ALTER TABLE users DROP credentials_expired");
        $this->addSql("ALTER TABLE users DROP credentials_expire_at");
        $this->addSql("DROP INDEX UNIQ_1483A5E992FC23A8");
        $this->addSql("DROP INDEX UNIQ_1483A5E9A0D96FBF");
        $this->addSql("CREATE UNIQUE INDEX uniq_1483a5e95e237e06 ON users (name)");
    }
}
