<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121026171424 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        
        $this->addSql("CREATE SEQUENCE contacts_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE contacts (id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_33401573A76ED395 ON contacts (user_id)");
        $this->addSql("ALTER TABLE contacts ADD CONSTRAINT FK_33401573A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE fos_user DROP shib_username");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("DROP SEQUENCE contacts_id_seq");
        $this->addSql("DROP TABLE contacts");
        $this->addSql("DROP INDEX IDX_33401573A76ED395");
        $this->addSql("ALTER TABLE fos_user ADD shib_username VARCHAR(255) DEFAULT NULL");
        $this->addSql("UPDATE fos_user SET shib_username = email");
    }
}
