<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121030125240 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user ADD encoder_name VARCHAR(15) DEFAULT NULL");
        
        $map = array ('salt' => 'salt', 'password' => 'password', 'encoder_name' => 'algoritmo');
        
        foreach($map as $target => $source) {
            $subquery = "SELECT u.$source FROM utente u WHERE u.id_utente = fu.id";
            
            $this->addSql("UPDATE fos_user fu SET $target = ($subquery) WHERE EXISTS($subquery)");
        }
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user DROP encoder_name");
    }
}
