<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121011120358 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE fos_user ADD given_name VARCHAR(160) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD surname VARCHAR(160) DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD person_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE fos_user ADD member_of VARCHAR(15) DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");

        $this->addSql("ALTER TABLE fos_user DROP given_name");
        $this->addSql("ALTER TABLE fos_user DROP surname");
        $this->addSql("ALTER TABLE fos_user DROP person_id");
        $this->addSql("ALTER TABLE fos_user DROP member_of");
    }
}
