<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121109124047 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->dropViews();
        $this->addSql('ALTER TABLE classi_materie ALTER desc_materia TYPE VARCHAR(200)');
        $this->createViews();
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->dropViews();
        $this->addSql('ALTER TABLE classi_materie ALTER desc_materia TYPE VARCHAR(150)');
        $this->createViews();
    }
    
    private function dropViews()
    {
        $this->addSql('DROP VIEW nome_insegnamenti');
    }
    
    private function createViews()
    {
        $sql =<<<EOT
CREATE VIEW nome_insegnamenti AS (
 SELECT i.id_canale, m.desc_materia, i.cod_ril, d.nome_doc, i.cod_corso, i.anno_accademico
   FROM insegnamenti i, classi_materie m, docente d
  WHERE i.cod_materia_ins::text = m.cod_materia::text AND i.cod_doc::text = d.cod_doc::text)
EOT;
        
        $this->addSql($sql);
    }
}
