<?php

namespace Universibo\Bundle\ContentBundle\Entity;

use Universibo\Bundle\CoreBundle\Entity\Channel;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findByChannel(Channel $channel, $limit = null)
    {
        $queryBuilder = $this
            ->createQueryBuilder('n')
            ->leftJoin('n.channels', 'c')
            ->where('c = :channel')
            ->orderBy('n.createdAt', 'DESC')
            ->setParameter('channel', $channel)
        ;

        if (is_int($limit)) {
            $queryBuilder->setMaxResults($limit);
        }

        return $queryBuilder->getQuery()->getResult();
    }
}
