<?php

namespace Universibo\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BetaRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetaRequestRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findPending()
    {
        return $this->findByApprovedAt(null);
    }
}
