<?php

namespace Universibo\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends EntityRepository
{
    /**
     * Saves a channel
     *
     * @param  Channel $channel
     * @return Channel
     */
    public function save(Channel $channel)
    {
        $em = $this->getEntityManager();
        $channel = $em->merge($channel);
        $em->flush($channel);

        return $channel;
    }

    public function findManyById(array $ids)
    {
        return $this
            ->createQueryBuilder('c')
            ->where('c.id IN (:ids)')
            ->setParameter('ids', $ids)
            ->getQuery()
            ->getResult()
        ;
    }
}
