<?php

namespace Universibo\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelServiceRepository extends EntityRepository
{
    /**
     * Finds or creates a service by name
     *
     * @param  string         $name
     * @return ChannelService
     */
    public function findOrCreateByName($name)
    {
        $channelService = $this->findOneByName($name);

        if (null === $channelService) {
            $channelService = new ChannelService();
            $channelService->setName($name);

            $em = $this->getEntityManager();
            $em->persist($channelService);
            $em->flush($channelService);
        }

        return $channelService;
    }
}
