<?php

namespace Universibo\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    /**
     * @param  Person $person
     * @return Person
     */
    public function save(Person $person)
    {
        $em = $this->getEntityManager();
        $person = $em->merge($person);
        $em->flush($person);

        return $person;
    }
}
