<?php

namespace Universibo\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Universibo\Bundle\MainBundle\Entity\UniboGroup;

/**
 * UniboGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniboGroupRepository extends EntityRepository
{
    /**
     * Finds a group from DB or creates it
     *
     * @param  string     $name
     * @return UniboGroup
     */
    public function findOrCreate($name)
    {
        $group = $this->findOneByName($name);

        if ($group === null) {
            $group = new UniboGroup();
            $group->setName($name);

            $em = $this->getEntityManager();
            $em->persist($group);
            $em->flush($group);
        }

        return $group;
    }
}
