<?php

namespace Universibo\Bundle\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChannelServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelServiceRepository extends EntityRepository
{
}
