<?php

namespace Universibo\Bundle\LegacyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatchRenameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatchRenameRepository extends EntityRepository
{
}
