universibo_main_homepage:
  pattern: /
  defaults: { _controller: 'UniversiboMainBundle:Default:index' }
rss:
  pattern: /rss/{idCanale}/
  defaults: { _controller: 'UniversiboMainBundle:Rss:index' }
  requirements: { idCanale: \d+ }
universibo_main_auth_failed:
  pattern: /auth-failed/
  defaults: { _controller: 'UniversiboMainBundle:AuthFailed:index' }
universibo_main_rules:
  pattern: /regolamento/
  defaults: { _controller: 'UniversiboMainBundle:Rules:index' }
universibo_main_rules_accept:
  pattern: /regolamento/accetta/
  defaults: { _controller: 'UniversiboMainBundle:Rules:accept' }
  requirements: { _method: POST }
universibo_main_suggestion_new:
  pattern: /suggerimento/
  defaults: { _controller: 'UniversiboMainBundle:Suggestion:new' }
universibo_main_suggestion_success:
  pattern: /suggerimento/grazie/
  defaults: { _controller: 'UniversiboMainBundle:Suggestion:success' }
universibo_main_profile_edit:
  pattern: /my/profile/
  defaults: { _controller: 'UniversiboMainBundle:Profile:edit' }
universibo_main_profile_update:
  pattern: /my/profile/update/
  defaults: { _controller: 'UniversiboMainBundle:Profile:update' }
  requirements: { _method: POST }
universibo_main_sitemap:
  pattern: /sitemap.xml
  defaults: { _controller: 'UniversiboMainBundle:Sitemap:index' }
universibo_main_contact_verify:
  pattern: /my/email/verify/{token}/
  defaults: { _controller: 'UniversiboMainBundle:Contact:verify' }
  requirements: { _method: GET }
universibo_main_contact_cancel:
  pattern: /my/email/cancel/{token}/
  defaults: { _controller: 'UniversiboMainBundle:Contact:cancel' }
  requirements: { _method: GET }
#universibo_main_school:
#  pattern: /scuole/{slug}/
#  defaults: { _controller: 'UniversiboMainBundle:School:index' }
universibo_main_username_available:
    pattern: /user/{username}/available
    defaults: { _controller: 'UniversiboMainBundle:User:available' }
universibo_main_beta_index:
  pattern: /beta/
  defaults: { _controller: 'UniversiboMainBundle:Beta:index' }
universibo_main_beta_pending:
  pattern: /beta/pending
  defaults: { _controller: 'UniversiboMainBundle:Beta:pending' }
universibo_main_beta_confirm:
  pattern: /beta/confirm
  defaults: { _controller: 'UniversiboMainBundle:Beta:confirm' }
