//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <NOME>
 * f1 -> ( <OPEN> listaParam() <CLOSE> )?
 * f2 -> ( <STAR> )?
 * f3 -> ( <COMMA> <NOME> ( <OPEN> listaParam() <CLOSE> )? ( <STAR> )? )*
 */
public class listaParam implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public NodeOptional f2;
   public NodeListOptional f3;

   public listaParam(NodeToken n0, NodeOptional n1, NodeOptional n2, NodeListOptional n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

