//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> <OUT>
 * f1 -> ( <OPEN> <CLOSE> )?
 * f2 -> listaParam()
 * f3 -> <STOP>
 */
public class outputFilter implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public listaParam f2;
   public NodeToken f3;

   public outputFilter(NodeToken n0, NodeOptional n1, listaParam n2, NodeToken n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public outputFilter(NodeOptional n0, listaParam n1) {
      f0 = new NodeToken("OUT");
      f1 = n0;
      f2 = n1;
      f3 = new NodeToken(";");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

